# This is a basic workflow to help you get started with Actions

name: ssh-agent

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      enabled:
        description: 'SSH Enable'     
        required: false
        default: "false"
      ssh-key:
        description: 'SSH key'     
        required: false
        default: "onstudy"
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Make sure the @v0.5.3 matches the current version of the
      # action 
      - uses: webfactory/ssh-agent@v0.5.3

